<a href="https://colab.research.google.com/github/heewon330/TIL3/blob/master/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1D=np.array([1,2,3,4])
arr1D


array([1, 2, 3, 4])

In [ ]:
arr1D.ndim #1차원

1

In [ ]:
arr1D.shape #1행4열

(4,)

In [ ]:
arr2D = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]           
])
arr2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2D.ndim

2

In [ ]:
arr2D.shape #(행=자료수,열=변수)

(3, 3)

In [ ]:
display(arr1D)
display(arr1D[0])
display(arr1D[1])
display(arr1D[-1])
display(arr1D[-2])


array([1, 2, 3, 4])

1

2

4

3

In [ ]:
display(arr1D[4])

IndexError: ignored

In [ ]:
for x in arr1D:
  print(x)

1
2
3
4


In [ ]:
display(min(arr1D))
display(max(arr1D))

1

4

In [ ]:
display(arr1D[:]) #슬라이스
display(arr1D[::-1])

array([1, 2, 3, 4])

array([4, 3, 2, 1])

In [ ]:
print(arr1D)
display(arr1D)

[1 2 3 4]


array([1, 2, 3, 4])

In [ ]:
display(arr2D)
display(arr2D[0,0])
display(arr2D[0,1])
display(arr2D[1,1])
display(arr2D[2,1])


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

1

2

5

8

In [ ]:
display(arr2D[0])
display(arr2D[0,])
display(arr2D[1])

array([1, 2, 3])

array([1, 2, 3])

array([4, 5, 6])

In [ ]:
display(arr2D[:,1]) #열만 인덱스할 때에는 슬라이스 사용

array([2, 5, 8])

In [ ]:
display(arr2D[1: ,1:])

array([[5, 6],
       [8, 9]])

In [ ]:
arrN = np.arange(1,31).reshape(3,10)
arrN

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [ ]:
display(arrN[1,5])
display(arrN[2,8])
display(arrN[1,3:6])
display(arrN[1: ,7])
display(arrN[ :2,8:])

16

29

array([14, 15, 16])

array([18, 28])

array([[ 9, 10],
       [19, 20]])

In [ ]:
arrn=np.arange(1,51).reshape(5,10)
arrn

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [ ]:
display(arrn[1:4,3:7])
display(arrn[1:4,1])

array([[14, 15, 16, 17],
       [24, 25, 26, 27],
       [34, 35, 36, 37]])

array([12, 22, 32])

In [ ]:
display(arr1D)
arr1D[np.array([True,False,False,False])]

array([1, 2, 3, 4])

array([1])

In [ ]:
display(arr1D>2)
display(arr1D[arr1D>2])

array([False, False,  True,  True])

array([3, 4])

In [ ]:
display(arr1D[arr1D%2==1])

array([1, 3])

In [ ]:
display(arr1D)
idx =np.array([1,1,1,1,1,1,1,0,0,0,0,2,2,2,3,3,3,2,1,1,1])
arr1D[idx]

array([1, 2, 3, 4])

array([2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 3, 3, 3, 4, 4, 4, 3, 2, 2, 2])

In [ ]:
[1,2,1.0 , 'string',[1,2,3]]

[1, 2, 1.0, 'string', [1, 2, 3]]

In [ ]:
arr1D.dtype #64:비트수

dtype('int64')

In [ ]:
arr=np.array([1,2,3,4,5.0])
display(arr)
display(arr.dtype)

array([1., 2., 3., 4., 5.])

dtype('float64')

In [ ]:
# 자료 타입 직접 결정
arr=np.array([1,2,3,4,5],dtype=np.float64)
display(arr)
display(arr.dtype)

array([1., 2., 3., 4., 5.])

dtype('float64')

In [ ]:
display(type(np.NaN))
display(np.array([0])/np.array([0]))

float

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan])

In [ ]:
display(type(np.inf))
display(np.log(0))

float

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


-inf

In [ ]:
np.zeros(10,dtype=np.int) #0으로 초기화된 배열

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones(10) #1로 초기화된 배열,타입은 실수

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,2,0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [ ]:
#주어진 구간에서 원하는 수만큼 균등한 간격으로 수열 만들어줌
display(np.linspace(0,10,15))
display(np.linspace(1,2,100))

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
       1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
       1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
       1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
       1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
       1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
       1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
       1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
       1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
       1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
       1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
       1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
       1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
       1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
       1.70707071, 1.71717172, 1.72727273, 1.73737374, 1.74747

In [ ]:
np.random.rand(10)
# 균등 분포를 통해 정해진 갯수만큼 수를 생성
# 실행할 때마다 매번 다른 값 나옴

array([0.82222577, 0.18691682, 0.0116755 , 0.0826648 , 0.2605181 ,
       0.07855094, 0.44352525, 0.13156829, 0.64002361, 0.09549156])

In [ ]:

np.random.randint(0,10, size=10)


array([4, 2, 7, 3, 7, 6, 2, 0, 9, 3])

In [ ]:
np.random.seed(100)
np.random.rand(10)

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886,
       0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333])

In [ ]:
#중복 없애기 replace=False
arr=np.arange(1,11)
np.random.choice(arr,size=5,replace=False)

array([ 7,  3,  9,  1, 10])

로또~~

In [ ]:
arr=np.arange(1,46)
np.random.choice(arr,size=6,replace=False)

array([ 6, 41, 12, 10, 24, 37])

In [ ]:
import numpy as np
arr1D=np.random.randint(0,10,size=4)
arr1D

array([3, 0, 4, 6])

In [ ]:
display(arr1D.reshape(2,2))
display(arr1D.reshape(-1,2))
display(arr1D.reshape(4,1))
display(arr1D.reshape(-1,1))

array([[3, 0],
       [4, 6]])

array([[3, 0],
       [4, 6]])

array([[3],
       [0],
       [4],
       [6]])

array([[3],
       [0],
       [4],
       [6]])

In [ ]:
display(arr1D.reshape(5,5))

ValueError: ignored

In [ ]:
arr2D=np.random.randint(1,10,size=(3,3))
arr2D

array([[8, 9, 9],
       [3, 6, 8],
       [8, 3, 6]])

In [ ]:
display(arr2D.flatten()) #행 기준으로 고차원에서 저차원으로
display(arr2D.ravel())

display(arr2D.flatten(order='F')) # 열 기준

array([8, 9, 9, 3, 6, 8, 8, 3, 6])

array([8, 9, 9, 3, 6, 8, 8, 3, 6])

array([8, 3, 8, 9, 6, 3, 9, 8, 6])

In [ ]:
np.ones((4,1))

array([[1.],
       [1.],
       [1.],
       [1.]])

In [ ]:
np.zeros((4,1))

array([[0.],
       [0.],
       [0.],
       [0.]])

In [ ]:
mat=np.random.randint(1,10,size=(3,5))
mat

array([[1, 4, 9, 4, 8],
       [9, 5, 1, 5, 1],
       [2, 7, 6, 7, 3]])

In [ ]:
vector=np.random.randint(1,10,size=(4,1))
vector

array([[9],
       [6],
       [7],
       [6]])

In [ ]:
2 * vector

array([[18],
       [12],
       [14],
       [12]])

In [ ]:
mat = np.random.randint(1,10,size=(3,4))
mat

array([[2, 1, 1, 2],
       [8, 1, 8, 7],
       [4, 1, 8, 9]])

In [ ]:
2*mat

array([[ 4,  2,  2,  4],
       [16,  2, 16, 14],
       [ 8,  2, 16, 18]])

In [ ]:
display(vector)
display(mat)

array([[9],
       [6],
       [7],
       [6]])

array([[2, 1, 1, 2],
       [8, 1, 8, 7],
       [4, 1, 8, 9]])

In [ ]:
vector = np.random.randint(10,size=(3,1))
vector

array([[1],
       [0],
       [5]])

In [ ]:
vector *mat

array([[ 2,  1,  1,  2],
       [ 0,  0,  0,  0],
       [20,  5, 40, 45]])

In [ ]:
vec1 = np.random.randint(1,10,size=(3,1))
vec2=np.random.randint(1,10,size=(3,1))
display(vec1,vec2)

array([[2],
       [1],
       [6]])

array([[9],
       [6],
       [8]])

In [ ]:
vec1*vec2

array([[18],
       [ 6],
       [48]])

In [ ]:
mat1 = np.random.randint(1,10,size=(2,2))
mat2=np.random.randint(1,10,size=(2,2))
display(mat1,mat2)

array([[9, 9],
       [7, 7]])

array([[8, 9],
       [7, 1]])

In [ ]:
mat1 *mat2

array([[72, 81],
       [49,  7]])